name: ðŸž Bug report
description: Create a report to help us improve
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        This issue form is for reporting bugs only! Please run this command first to see if your problem has been solved, otherwise open the issue:
        `~/klipper-backup/script.sh --fix`
        If you have a feature request, please use [feature_request](/Staubgeborener/klipper-backup/issues/new?assignees=&labels=feature+request&projects=&template=feature_request.yml&title=%5BFeature+request%5D%3A+). Please use [markdown syntax](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code).
  - type: checkboxes
    attributes:
      label: Code of Conduct
      options:
        - label: I promise that i have used markdown syntax to make the code more readable which helps to fix the problem and that I have tested the --fix command mentioned above without success.
          required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened
      description: >-
        A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: What did you expect to happen
      description: >-
        A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    id: repro-steps
    attributes:
      label: How to reproduce
      description: >-
        Minimal and precise steps to reproduce this bug.
    validations:
      required: true
  - type: textarea
    id: debug-output
    attributes:
      label: Debug
      description: >-
        Insert here the output of `~/klipper-backup/script.sh --debug` (DO NOT USE MARKDOWN HERE)
      render: shell
    validations:
      required: true
  - type: textarea
    id: additional-info
    attributes:
      label: Additional information
      description: |
        If you have any additional information for us, use the field below.

        Please note, you can attach screenshots or screen recordings here, by
        dragging and dropping files in the field below.
