name: Bug report
description: Create a report to help us improve
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        This issue form is for reporting bugs only!
        If you have a feature request, please use [feature_request](/Staubgeborener/klipper-backup/issues/new?assignees=&labels=feature+request&projects=&template=feature_request.yml&title=%5BFeature+request%5D%3A+). Please use [markdown syntax](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code).
  - type: textarea
    id: what-happened
    attributes:
      label: What happened
      description: >-
        A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: What did you expect to happen
      description: >-
        A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    id: repro-steps
    attributes:
      label: How to reproduce
      description: >-
        Minimal and precise steps to reproduce this bug.
    validations:
      required: true
  - type: textarea
    id: additional-info
    attributes:
      label: Additional information
      description: |
        If you have any additional information for us, use the field below.

        Please note, you can attach screenshots or screen recordings here, by
        dragging and dropping files in the field below.