name: Feature request
description: Suggest an idea for this project
title: "[Feature request]: "
labels: ["feature request"]
body:
  - type: markdown
    attributes:
      value: |
        This issue form is for feature requests only!
        If you have a bug report, please use [bug_report](/Staubgeborener/klipper-backup/issues/new?assignees=&labels=bug&projects=&template=bug_report.yml&title=%5BBug%5D%3A+). Please use [markdown syntax](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code).
  - type: textarea
    id: related-to-problem
    attributes:
      label: Is your feature request related to a problem? Please describe.
      description: >-
        A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
    validations:
      required: true
  - type: textarea
    id: describe-solution
    attributes:
      label: Describe the solution you'd like
      description: >-
        A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: >-
        A clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: true
  - type: textarea
    id: additional-info
    attributes:
      label: Additional information
      description: |
        If you have any additional information for us, use the field below.

        Please note, you can attach screenshots or screen recordings here, by
        dragging and dropping files in the field below.
